dist: focal
language: bash
sudo: required
group: edge
arch: arm64-graviton2
virt: vm

addons:
  snaps:
   - name: snapcraft
     channel: stable
     confinement: classic
   - name: lxd
     channel: stable
  apt:
    packages:
      - python3  
      - python3-pip   


jobs:
  - arch: amd64
  - arch: arm64 
  - dist: focal
    language: bash
    sudo: required
    group: edge
    arch: arm64-graviton2
    virt: vm
script:
  - sudo chmod 666 /etc/subuid
  - sudo chmod 666 /etc/subgid
  - echo "root:1000000:65536" >> /etc/subgid
  - echo "root:1000000:65536" >> /etc/subgid
  - sudo echo "root:1000000:65536" >> sudo /etc/subuid
  - sudo echo "root:1000000:65536" >> sudo /etc/subgid
  - cat /etc/subuid
  - cat /etc/subgid
  - sudo /snap/bin/lxd.migrate -yes
  - sudo /snap/bin/lxd waitready
  - sudo /snap/bin/lxd init --auto
  - sudo usermod --append --groups lxd $USER
  - sg lxd -c 'SNAPCRAFT_ENABLE_DEVELOPER_DEBUG=yes snapcraft --use-lxd'
  - sudo apt update
  - sudo snap install *.snap --classic --dangerous
  - sudo pip3 install --upgrade pip
  - sudo pip3 install -U pytest
  - pwd
  - ps -ef
  - ls -l
  - ./tests/smoke-test.sh
  - export UNDER_TIME_PRESSURE="True"
  - (cd tests; pytest -s verify-branches.py)
  - travis_wait 20 cd tests; sudo -E pytest -s -ra test-addons.py
